#!/bin/bash

VERSION=0.14.1_1
GIT_ROOT=$(git rev-parse --show-toplevel)

docker run -d \
                --restart=always \
		-p 34197:34197/udp \
                -v ${GIT_ROOT}/config:/opt/factorio/config \
                -v ${GIT_ROOT}/saves:/opt/factorio/saves \
		--name factorio \
		factorio-baseimage:${VERSION}
