#!/bin/bash
docker run -d \
                --restart=always \
		-p 34197:34197/udp \
                -v /home/terry/docker/factorio-baseimage/config:/opt/factorio/config \
                -v /home/terry/docker/factorio-baseimage/saves:/opt/factorio/saves \
		--name factorio \
		factorio-baseimage:0.13.2_1
