#!/bin/bash

/opt/factorio/bin/x64/factorio --create /opt/factorio/saves/initial-save --map-gen-settings /opt/factorio/config/map-gen-settings.json;
/opt/factorio/bin/x64/factorio --server-settings /opt/factorio/config/server-settings.json --start-server /opt/factorio/saves/initial-save.zip
